# Generated by Django 5.1.2 on 2024-10-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArticleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="До 255 символов",
                        max_length=255,
                        verbose_name="Навзание",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="До 255 символов",
                        max_length=255,
                        verbose_name="Навзание",
                    ),
                ),
                ("params", models.JSONField(verbose_name="Параметры")),
            ],
            options={
                "verbose_name": "Карточка",
                "verbose_name_plural": "Карточки",
            },
        ),
    ]
