# Generated by Django 5.1.2 on 2024-10-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_articlemodel_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="status",
            field=models.BooleanField(null=True),
        ),
    ]
