# Generated by Django 5.1.2 on 2024-11-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0003_card_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="test_app.articlemodel",
            ),
        ),
    ]
