# Generated by Django 5.1.2 on 2024-11-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0004_card_article"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="articlemodel",
            index=models.Index(fields=["title"], name="test_app_ar_title_4c5fb7_idx"),
        ),
    ]
