# Generated by Django 5.1.2 on 2024-11-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0005_articlemodel_test_app_ar_title_4c5fb7_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="articlemodel",
            name="test_app_ar_title_4c5fb7_idx",
        ),
        migrations.AddIndex(
            model_name="articlemodel",
            index=models.Index(
                fields=["title", "description"], name="test_app_ar_title_83f14a_idx"
            ),
        ),
    ]
