# Generated by Django 5.1.2 on 2024-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_spa_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='До 255 символов', max_length=255, verbose_name='Навзание')),
                ('params', models.JSONField(verbose_name='Параметры')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='Article',
        ),
    ]
