# Generated by Django 5.1.2 on 2024-10-19 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_spa_admin', '0002_card_rename_articlemodel_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='ArticleModel',
        ),
    ]
